# Generated by scripts/generate_types.py; schemas are the source of truth.
from typing import Any, Dict, List, Literal, Optional, TypedDict

class Artifact(TypedDict):
    artifact_id: str
    uri: str
    sha256: str
    bytes: int
    kind: Literal['RAW_PROF', 'CSV', 'TRACE', 'SIDECAR', 'LOG', 'ENVIRONMENT']
    created_at: str
    redacted: bool
    media_type: str
    schema_version: Literal[1]
    extensions: Dict[str, Any]
    protocol_version: Literal['latency-v1']

class Attempt(TypedDict):
    attempt_id: str
    session_id: str
    task_id: str
    case_key: str
    ordinal: int
    started_at: str
    ended_at: Optional[str]
    state: Literal['RUNNING', 'SUCCEEDED', 'REJECTED', 'FAILED', 'INTERRUPTED']
    exit_code: Optional[int]
    process_group: Optional[int]
    release_status: Literal['NOT_CHECKED', 'RELEASED', 'RESIDUAL', 'UNKNOWN']
    released_at: Optional[str]
    evidence_ids: List[str]
    reason: Optional[str]
    schema_version: Literal[1]
    extensions: Dict[str, Any]
    protocol_version: Literal['latency-v1']

class CaseInputsItem(TypedDict):
    shape: List[int]
    dtype: str
    layout: str
    stride: Optional[List[int]]

class CaseOutputsItem(TypedDict):
    shape: List[int]
    dtype: str
    layout: str
    stride: Optional[List[int]]

class CaseInputGeneration(TypedDict):
    algorithm: str
    version: str
    seed: int
    input_sha256: Optional[str]

class Case(TypedDict):
    operator: str
    inputs: List[CaseInputsItem]
    outputs: List[CaseOutputsItem]
    attributes: Dict[str, Any]
    input_generation: CaseInputGeneration
    semantic_version: str
    protocol_version: Literal['latency-v1']
    schema_version: Literal[1]
    extensions: Dict[str, Any]

class Fact(TypedDict):
    value: Optional[str]
    status: Literal['KNOWN', 'UNKNOWN', 'PERMISSION_DENIED', 'UNSUPPORTED', 'PARSE_ERROR', 'NOT_FOUND', 'TIMEOUT', 'COMMAND_FAILED']
    reason: Optional[str]
    source: List[str]
    confidence: Literal['VERIFIED', 'DECLARED_ONLY', 'LOCATION_ONLY', 'NONE']

class Device(TypedDict):
    device_uid: str
    card_uid: str
    identity_confidence: Literal['STABLE_CHIP', 'LOCATION_ONLY']
    card_identity_confidence: Literal['LOCATION_ONLY']
    npu_id: int
    chip_id: int
    logical_id: int
    chip_name_raw: str
    soc_family: Fact
    hardware_bin: Fact
    bin_mapping_version: str
    board_id: Fact
    pcie: Fact
    hbm_mb: Fact
    firmware: Fact

class Library(TypedDict):
    name: str
    role: str
    version: Fact
    resolved_path: Optional[str]
    package_id: Optional[str]
    repository_url: Optional[str]
    git_commit: Optional[str]
    dirty_tree_sha256: Optional[str]
    artifact_sha256: Optional[str]
    load_status: Literal['DECLARED_ONLY', 'VERIFIED', 'NOT_FOUND']
    used_by_case: List[str]

class Support(TypedDict):
    library: str
    revision: Optional[str]
    soc: Optional[str]
    hardware_bin: Optional[str]
    cann: Optional[str]
    python: Optional[str]
    torch_npu: Optional[str]
    preset: str
    status: Literal['VERIFIED', 'UNSUPPORTED', 'UNVERIFIED']
    reason: str
    verified_at: Optional[str]
    evidence_ids: List[str]

class Command(TypedDict):
    evidence_id: str
    argv: List[str]
    started_at: str
    duration_seconds: float
    exit_code: Optional[int]
    stdout: str
    stderr: str
    execution_status: Literal['KNOWN', 'UNKNOWN', 'PERMISSION_DENIED', 'UNSUPPORTED', 'PARSE_ERROR', 'NOT_FOUND', 'TIMEOUT', 'COMMAND_FAILED']
    parse_status: Literal['KNOWN', 'UNKNOWN', 'PERMISSION_DENIED', 'UNSUPPORTED', 'PARSE_ERROR', 'NOT_FOUND', 'TIMEOUT', 'COMMAND_FAILED']
    reason: Optional[str]
    permission_scope: str
    parser_version: str
    redacted: bool
    output_sha256: str

class EnvironmentHost(TypedDict):
    hostname: Fact
    architecture: Fact
    kernel: Fact
    os: Fact
    cpu_numa: Fact

class EnvironmentSoftwarePackagesItem(TypedDict):
    name: str
    version: Fact

class EnvironmentSoftware(TypedDict):
    npu_smi: Fact
    driver: Fact
    firmware: Fact
    toolkit: Fact
    msprof: Fact
    python: Fact
    search_paths: Dict[str, Any]
    packages: List[EnvironmentSoftwarePackagesItem]
    operator_libraries: List[Library]

class Environment(TypedDict):
    environment_id: str
    server_id: str
    captured_at: str
    parser_version: str
    redacted: bool
    host: EnvironmentHost
    device_inventory: Fact
    devices: List[Device]
    software: EnvironmentSoftware
    support_matrix: List[Support]
    evidence: List[Command]
    schema_version: Literal[1]
    extensions: Dict[str, Any]
    protocol_version: Literal['latency-v1']

class ObservationMetric(TypedDict):
    name: Literal['task_duration_us', 'device_span_us', 'device_critical_path_us', 'host_elapsed_us', 'rank_elapsed_us']
    unit: Literal['us']
    boundary: str
    definition_version: str

class Observation(TypedDict):
    observation_id: str
    profile_id: str
    attempt_id: str
    session_id: str
    environment_id: str
    device_uid: str
    task_id: str
    case_key: str
    input_sha256: Optional[str]
    seed: int
    round: int
    iteration: int
    rank: int
    phase: Literal['MEASURE']
    task_ids: List[str]
    metric: ObservationMetric
    raw_samples: List[float]
    completeness: Literal['COMPLETE', 'PARTIAL', 'MISSING']
    quality: List[Literal['VALID', 'CONTENDED', 'UNSTABLE', 'THERMAL_DRIFT', 'VERSION_CHANGED', 'METADATA_INCOMPLETE', 'INSUFFICIENT_DATA', 'ATTRIBUTION_UNKNOWN', 'TRACE_MISSING', 'UNIT_UNKNOWN']]
    schema_version: Literal[1]
    extensions: Dict[str, Any]
    protocol_version: Literal['latency-v1']

class Plan(TypedDict):
    plan_id: str
    plan_sha256: str
    case_manifest_sha256: str
    policy_id: str
    policy_version: int
    valid_from: str
    valid_until: str
    case_keys: List[str]
    preset: str
    budget_seconds: float
    cleanup_reserve_seconds: float
    priorities: Dict[str, Any]
    schema_version: Literal[1]
    extensions: Dict[str, Any]
    protocol_version: Literal['latency-v1']

class ProfileTaskMappingItem(TypedDict):
    iteration: int
    rank: int
    task_ids: List[str]

class Profile(TypedDict):
    profile_id: str
    attempt_id: str
    case_key: str
    preset: str
    preset_sha256: str
    collector_version: Fact
    exporter_version: Fact
    parser_version: str
    artifact_ids: List[str]
    final_argv: List[str]
    completeness: Literal['COMPLETE', 'PARTIAL', 'MISSING']
    export_status: Literal['KNOWN', 'UNKNOWN', 'PERMISSION_DENIED', 'UNSUPPORTED', 'PARSE_ERROR', 'NOT_FOUND', 'TIMEOUT', 'COMMAND_FAILED']
    attribution_status: Literal['KNOWN', 'UNKNOWN', 'PERMISSION_DENIED', 'UNSUPPORTED', 'PARSE_ERROR', 'NOT_FOUND', 'TIMEOUT', 'COMMAND_FAILED']
    expected_task_count: int
    actual_task_count: Optional[int]
    task_mapping: List[ProfileTaskMappingItem]
    quality: List[Literal['VALID', 'CONTENDED', 'UNSTABLE', 'THERMAL_DRIFT', 'VERSION_CHANGED', 'METADATA_INCOMPLETE', 'INSUFFICIENT_DATA', 'ATTRIBUTION_UNKNOWN', 'TRACE_MISSING', 'UNIT_UNKNOWN']]
    reason: Optional[str]
    schema_version: Literal[1]
    extensions: Dict[str, Any]
    protocol_version: Literal['latency-v1']

class SessionResourceLedgerItem(TypedDict):
    device_uid: str
    start_monotonic_ns: int
    end_monotonic_ns: Optional[int]

class Session(TypedDict):
    session_id: str
    server_id: str
    device_uids: List[str]
    environment_id: str
    plan_id: str
    plan_sha256: str
    release_id: str
    policy_id: str
    policy_version: int
    window_id: str
    started_at: str
    ended_at: Optional[str]
    state: Literal['RUNNING', 'COMPLETED', 'PARTIAL', 'SKIPPED', 'FAILED']
    resource_ledger: List[SessionResourceLedgerItem]
    reason: Optional[str]
    schema_version: Literal[1]
    extensions: Dict[str, Any]
    protocol_version: Literal['latency-v1']
