"""Generate Python TypedDict contracts from the checked-in schema definitions."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
lines = ['# Generated by scripts/generate_types.py; schemas are the source of truth.',
         'from typing import Any, Dict, List, Literal, Optional, TypedDict', '']
written = set()
def typename(name): return ''.join(p.title() for p in name.replace('-', '_').split('_'))
def annotation(schema, name):
    if '$ref' in schema: return typename(schema['$ref'].split('/')[-1])
    if 'const' in schema: return 'Literal[' + repr(schema['const']) + ']'
    if 'enum' in schema: return 'Literal[' + ', '.join(repr(v) for v in schema['enum']) + ']'
    if 'anyOf' in schema: return 'Optional[' + annotation(schema['anyOf'][0], name) + ']'
    kind = schema.get('type')
    if kind == 'object':
        if 'properties' not in schema: return 'Dict[str, Any]'
        emit(name, schema)
        return name
    if kind == 'array': return 'List[' + annotation(schema['items'], name + 'Item') + ']'
    return dict(string='str', integer='int', number='float', boolean='bool', null='None').get(kind, 'Any')
def emit(name, schema):
    if name in written: return
    written.add(name)
    props = [(key, annotation(value, name + typename(key))) for key, value in schema['properties'].items()]
    lines.append('class ' + name + '(TypedDict):')
    lines.extend('    ' + key + ': ' + value for key, value in props)
    lines.append('')
for path in sorted((root / 'kernelx/schemas').glob('*.json')):
    schema = json.loads(path.read_text())
    for name, value in schema['$defs'].items(): emit(typename(name), value)
    emit(typename(path.stem), schema)
(root / 'kernelx/types.py').write_text('\n'.join(lines).rstrip() + '\n')
